### ISSUE TITLE
ARIA tab example

### ISSUE THREAD

**Issue by mhulse** [mhulse/jquery-nutshell#1]
HTML:

``` html
<ul role="tablist">
    <li role="presentation"><a href="#section1" tabindex="0" role="tab" aria-controls="panel1" aria-selected="true">Section 1</a></li>
    <li role="presentation"><a href="#section2" tabindex="-1" role="tab" aria-controls="panel2">Section 2</a></li>
    <li role="presentation"><a href="#section3" tabindex="-1" role="tab" aria-controls="panel2">Section 3</a></li>
</ul>
<section id="section1" tabindex="0" role="tabpanel">...</section>
<section id="section2" tabindex="0" role="tabpanel" aria-hidden="true">...</section>
<section id="section3" tabindex="0" role="tabpanel" aria-hidden="true">...</section>
```

... and the [JS](http://heydonworks.com/practical_aria_examples/js/a11y.js):

``` js
/* 4. Tab Interface 
-----------------------------------------------------------------------------------------
*/

// The class for the container div

var $container = '.tab-interface';

// The setup

$($container +' ul').attr('role','tablist');
$($container +' [role="tablist"] li').attr('role','presentation');
$('[role="tablist"] a').attr({
    'role' : 'tab', 
    'tabindex' : '-1'
});

// Make each aria-controls correspond id of targeted section (re href)

$('[role="tablist"] a').each(function() {
  $(this).attr(
    'aria-controls', $(this).attr('href').substring(1)
  );
});

// Make the first tab selected by default and allow it focus

$('[role="tablist"] li:first-child a').attr({
    'aria-selected' : 'true',
    'tabindex' : '0'
});

// Make each section focusable and give it the tabpanel role

$($container +' section').attr({
  'tabindex' : '0',
  'role' : 'tabpanel'
});

// Make all but the first section hidden (ARIA state and display CSS)

$('[role="tabpanel"]:not(:first-of-type)').attr({
  'aria-hidden' : 'true'
});


// Change focus between tabs with arrow keys

$('[role="tab"]').on('keydown', function(e) {

  // define current, previous and next (possible) tabs

  var $original = $(this);
  var $prev = $(this).parents('li').prev().children('[role="tab"]');
  var $next = $(this).parents('li').next().children('[role="tab"]');
  var $target;

  // find the direction (prev or next)

  switch (e.keyCode) {
    case 37:
      $target = $prev;
      break;
    case 39:
      $target = $next;
      break;
    default:
      $target = false
      break;
  }

  if ($target.length) {
      $original.attr({
        'tabindex' : '-1', 
        'aria-selected' : null
      });
      $target.attr({
        'tabindex' : '0',
        'aria-selected' : true
      }).focus();
  }

  // Hide panels

  $($container +' [role="tabpanel"]')
    .attr('aria-hidden', 'true');

  // Show panel which corresponds to target

  $('#' + $(document.activeElement).attr('href').substring(1))
    .attr('aria-hidden', null);

});

// Handle click on tab to show + focus tabpanel

$('[role="tab"]').on('click', function(e) {

  e.preventDefault();

  // remove focusability [sic] and aria-selected

  $('[role="tab"]').attr({
    'tabindex': '-1',
    'aria-selected' : null
    });

  // replace above on clicked tab

  $(this).attr({
    'aria-selected' : true,
    'tabindex' : '0'
  });

  // Hide panels

  $($container +' [role="tabpanel"]').attr('aria-hidden', 'true');

  // show corresponding panel

  $('#' + $(this).attr('href').substring(1))
    .attr('aria-hidden', null)
    .focus();

});
```

[CSS](http://heydonworks.com/practical_aria_examples/css/a11y.css):

``` css
/* 4. Simple tab interface */

a[role="tab"] {
    background: #1928CF;
    color: #fff;
    padding: 0.75em 0.33em;
    display: inline-block;
    margin-right: 0.25em;
}

a[aria-selected], a[role="tab"]:focus {
    background: #fff;
    color: #222;
    border: 2px solid #222;
    border-bottom: 0;
    position: relative;
    top: 2px;
}

a[role="tab"]:focus {
    background: #eee;
}

[role="tablist"] li {
    display: inline-block;
    list-style: none;
}

[role="tabpanel"] {
    margin-top: 0;
    padding: 1.5em;
    border: 2px solid #222;
}

[role="tabpanel"][aria-hidden="true"] {
    display: none;
}

[role="tabpanel"]:focus {
    background: #eee;
    outline: thin dotted;
}

/* 5. Alert! You're offline */

#status {
    padding: 1.5em;
    background: #5B7751;
    color: #fff;
}

#status.offline {
    background: #BF5050;
}
```

Above found here:

http://heydonworks.com/practical_aria_examples/
