### ISSUE TITLE
Simple tabs example

### ISSUE THREAD

**Issue by mhulse** [mhulse/jquery-nutshell#2]
HTML:

``` html
<section>

    <h1>FOO &amp; BAR</h1>

    <ul class="tabs">
        <li><a href="#tab1">FOO</a></li>
        <li><a href="#tab2">BAR</a></li>
    </ul>

    <div id="tab1">

        <p>FOO</p>

    </div>

    <div id="tab2">

        <p>BAR</p>

    </div>

</section>
```

CSS:

``` css
.tabs,
.tabs li {
    margin: 0;
    padding: 0;
}
.tabs {
    font-family: Arial, sans-serif;
    font-size: smaller;
    margin: 10px 0;
}
.tabs li {
    list-style: none;
    display: inline;
}
.tabs a {
    padding: 5px 10px;
    display: inline-block;
    background: #eee;
    color: #666;
    text-decoration: none;
}
.tabs a.active {
    background: #666;
    color:#fff;
}
```

JS:

``` js
$(document).ready(function() {

    /**
     * http://www.jacklmoore.com/notes/jquery-tabs/
     */

    $('ul.tabs').each(function() {

        // For each set of tabs, we want to keep track of
        // which tab is active and it's associated content
        var $active,
            $content,
            $links = $(this).find('a');

        // If the location.hash matches one of the links, use that as the active tab.
        // If no match is found, use the first link as the initial active tab.
        $active = $($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
        $active.addClass('active');
        $content = $($active.attr('href'));

        // Hide the remaining content
        $links.not($active).each(function () {
            $($(this).attr('href')).hide();
        });

        // Bind the click event handler
        $(this).on('click', 'a', function(e) {

            // Make the old tab inactive.
            $active.removeClass('active');
            $content.hide();

            // Update the variables with the new link and content
            $active = $(this);
            $content = $($(this).attr('href'));

            // Make the tab active.
            $active.addClass('active');
            $content.show();

            // Prevent the anchor's default click action
            e.preventDefault();

        });

    });

});
```

Above copied from: https://github.com/registerguard/bulldog/issues/55

The goal is to combine the above with code found in #1.
