### ISSUE TITLE
How to disable tab?

### ISSUE THREAD

**Issue by mhulse** [mhulse/jquery-nutshell#21]
There's CSS:

```css
.disabled {
    pointer-events: none;
    cursor: default;
    opacity: 0.6;
}
```

But might be nice to have a JS/programatic option?
